-- Reconcile the historical SQL migration chain with the current Prisma schema.
-- Generated by Prisma 5.22.0 from an isolated, empty Supabase verification schema
-- after applying migrations 000-023. The source drift was reviewed before this
-- forward-only migration was added; historical migration files remain unchanged.

-- DropForeignKey
ALTER TABLE "default_dimension_assignments" DROP CONSTRAINT "default_dimension_assignments_attribute_id_fkey";

-- DropForeignKey
ALTER TABLE "default_dimension_assignments" DROP CONSTRAINT "default_dimension_assignments_value_id_fkey";

-- DropForeignKey
ALTER TABLE "dimension_rules" DROP CONSTRAINT "dimension_rules_account_id_fkey";

-- DropForeignKey
ALTER TABLE "dimension_rules" DROP CONSTRAINT "dimension_rules_attribute_id_fkey";

-- DropForeignKey
ALTER TABLE "dimension_rules" DROP CONSTRAINT "dimension_rules_fixed_value_id_fkey";

-- DropForeignKey
ALTER TABLE "dimension_values" DROP CONSTRAINT "dimension_values_attribute_id_fkey";

-- DropForeignKey
ALTER TABLE "employees" DROP CONSTRAINT "employees_department_id_fkey";

-- DropForeignKey
ALTER TABLE "factura_lines" DROP CONSTRAINT "factura_lines_factura_id_fkey";

-- DropForeignKey
ALTER TABLE "factura_lines" DROP CONSTRAINT "factura_lines_item_tax_group_id_fkey";

-- DropForeignKey
ALTER TABLE "factura_lines" DROP CONSTRAINT "factura_lines_product_id_fkey";

-- DropForeignKey
ALTER TABLE "factura_lines" DROP CONSTRAINT "factura_lines_sales_order_line_id_fkey";

-- DropForeignKey
ALTER TABLE "factura_lines" DROP CONSTRAINT "factura_lines_variant_id_fkey";

-- DropForeignKey
ALTER TABLE "journal_entries" DROP CONSTRAINT "journal_entries_corrects_entry_id_fkey";

-- DropForeignKey
ALTER TABLE "journal_lines" DROP CONSTRAINT "journal_lines_dimension_1_id_fkey";

-- DropForeignKey
ALTER TABLE "journal_lines" DROP CONSTRAINT "journal_lines_dimension_2_id_fkey";

-- DropForeignKey
ALTER TABLE "journal_lines" DROP CONSTRAINT "journal_lines_dimension_3_id_fkey";

-- DropForeignKey
ALTER TABLE "journal_lines" DROP CONSTRAINT "journal_lines_dimension_4_id_fkey";

-- DropForeignKey
ALTER TABLE "operating_units" DROP CONSTRAINT "operating_units_manager_employee_id_fkey";

-- DropForeignKey
ALTER TABLE "operating_units" DROP CONSTRAINT "operating_units_parent_id_fkey";

-- DropForeignKey
ALTER TABLE "product_dimension_group_lines" DROP CONSTRAINT "product_dimension_group_lines_dimension_id_fkey";

-- DropForeignKey
ALTER TABLE "product_dimension_group_lines" DROP CONSTRAINT "product_dimension_group_lines_group_id_fkey";

-- DropForeignKey
ALTER TABLE "product_dimension_value_group_members" DROP CONSTRAINT "product_dimension_value_group_members_group_id_fkey";

-- DropForeignKey
ALTER TABLE "product_dimension_value_group_members" DROP CONSTRAINT "product_dimension_value_group_members_value_id_fkey";

-- DropForeignKey
ALTER TABLE "product_dimension_value_groups" DROP CONSTRAINT "product_dimension_value_groups_dimension_id_fkey";

-- DropForeignKey
ALTER TABLE "product_dimension_values" DROP CONSTRAINT "product_dimension_values_dimension_id_fkey";

-- DropForeignKey
ALTER TABLE "product_parameters" DROP CONSTRAINT "product_parameters_default_dimension_group_id_fkey";

-- DropForeignKey
ALTER TABLE "product_variant_values" DROP CONSTRAINT "product_variant_values_dimension_id_fkey";

-- DropForeignKey
ALTER TABLE "product_variant_values" DROP CONSTRAINT "product_variant_values_value_id_fkey";

-- DropForeignKey
ALTER TABLE "product_variant_values" DROP CONSTRAINT "product_variant_values_variant_id_fkey";

-- DropForeignKey
ALTER TABLE "products" DROP CONSTRAINT "products_dimension_group_id_fkey";

-- DropForeignKey
ALTER TABLE "purchase_order_lines" DROP CONSTRAINT "purchase_order_lines_variant_id_fkey";

-- DropForeignKey
ALTER TABLE "purchase_orders" DROP CONSTRAINT "purchase_orders_site_id_fkey";

-- DropForeignKey
ALTER TABLE "sales_order_lines" DROP CONSTRAINT "sales_order_lines_variant_id_fkey";

-- DropForeignKey
ALTER TABLE "sales_parameters" DROP CONSTRAINT "sales_parameters_default_warehouse_id_fkey";

-- DropForeignKey
ALTER TABLE "trade_agreements" DROP CONSTRAINT "trade_agreements_customer_id_fkey";

-- DropForeignKey
ALTER TABLE "trade_agreements" DROP CONSTRAINT "trade_agreements_item_group_id_fkey";

-- DropForeignKey
ALTER TABLE "trade_agreements" DROP CONSTRAINT "trade_agreements_product_id_fkey";

-- DropForeignKey
ALTER TABLE "trade_agreements" DROP CONSTRAINT "trade_agreements_supplier_id_fkey";

-- DropForeignKey
ALTER TABLE "trade_agreements" DROP CONSTRAINT "trade_agreements_variant_id_fkey";

-- DropForeignKey
ALTER TABLE "warehouse_parameters" DROP CONSTRAINT "warehouse_parameters_default_receive_location_id_fkey";

-- DropForeignKey
ALTER TABLE "warehouse_parameters" DROP CONSTRAINT "warehouse_parameters_warehouse_id_fkey";

-- DropIndex
DROP INDEX "purchase_orders_tenant_site_idx";

-- DropIndex
DROP INDEX "sales_orders_tenant_site_idx";

-- DropIndex
DROP INDEX "sales_orders_tenant_warehouse_idx";

-- DropIndex
DROP INDEX "tax_codes_tenant_applies_to_idx";

-- AlterTable
ALTER TABLE "default_dimension_assignments" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "dimension_attributes" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "dimension_rules" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "dimension_values" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "factura_lines" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "geo_points" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "resolved_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" DROP DEFAULT,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "inventory_transactions" ALTER COLUMN "physical_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "financial_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "operating_units" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "product_dimension_groups" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "product_dimension_value_groups" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "product_dimension_values" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "product_dimensions" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "product_parameters" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "trade_agreements" ALTER COLUMN "valid_from" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "warehouse_parameters" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- CreateIndex
-- Migration 013 created the equivalent nullable-column uniqueness as a partial
-- index. Prisma models it as a regular unique index, and PostgreSQL permits
-- multiple NULL values in both forms. Replace the old definition explicitly
-- because Prisma's generated diff cannot create a same-named replacement.
DROP INDEX "journal_entries_corrects_entry_id_key";

CREATE UNIQUE INDEX "journal_entries_corrects_entry_id_key" ON "journal_entries"("corrects_entry_id");

-- RenameForeignKey
ALTER TABLE "inventory_cost_layers" RENAME CONSTRAINT "inventory_batches_location_id_fkey" TO "inventory_cost_layers_location_id_fkey";

-- RenameForeignKey
ALTER TABLE "inventory_cost_layers" RENAME CONSTRAINT "inventory_batches_product_id_fkey" TO "inventory_cost_layers_product_id_fkey";

-- RenameForeignKey
ALTER TABLE "inventory_cost_layers" RENAME CONSTRAINT "inventory_batches_variant_id_fkey" TO "inventory_cost_layers_variant_id_fkey";

-- AddForeignKey
ALTER TABLE "warehouse_parameters" ADD CONSTRAINT "warehouse_parameters_warehouse_id_fkey" FOREIGN KEY ("warehouse_id") REFERENCES "warehouses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "warehouse_parameters" ADD CONSTRAINT "warehouse_parameters_default_receive_location_id_fkey" FOREIGN KEY ("default_receive_location_id") REFERENCES "warehouse_locations"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_dimension_values" ADD CONSTRAINT "product_dimension_values_dimension_id_fkey" FOREIGN KEY ("dimension_id") REFERENCES "product_dimensions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_dimension_value_groups" ADD CONSTRAINT "product_dimension_value_groups_dimension_id_fkey" FOREIGN KEY ("dimension_id") REFERENCES "product_dimensions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_dimension_value_group_members" ADD CONSTRAINT "product_dimension_value_group_members_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "product_dimension_value_groups"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_dimension_value_group_members" ADD CONSTRAINT "product_dimension_value_group_members_value_id_fkey" FOREIGN KEY ("value_id") REFERENCES "product_dimension_values"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_dimension_group_lines" ADD CONSTRAINT "product_dimension_group_lines_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "product_dimension_groups"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_dimension_group_lines" ADD CONSTRAINT "product_dimension_group_lines_dimension_id_fkey" FOREIGN KEY ("dimension_id") REFERENCES "product_dimensions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_variant_values" ADD CONSTRAINT "product_variant_values_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_variant_values" ADD CONSTRAINT "product_variant_values_dimension_id_fkey" FOREIGN KEY ("dimension_id") REFERENCES "product_dimensions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_variant_values" ADD CONSTRAINT "product_variant_values_value_id_fkey" FOREIGN KEY ("value_id") REFERENCES "product_dimension_values"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_parameters" ADD CONSTRAINT "product_parameters_default_dimension_group_id_fkey" FOREIGN KEY ("default_dimension_group_id") REFERENCES "product_dimension_groups"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "products" ADD CONSTRAINT "products_dimension_group_id_fkey" FOREIGN KEY ("dimension_group_id") REFERENCES "product_dimension_groups"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_site_id_fkey" FOREIGN KEY ("site_id") REFERENCES "sites"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_order_lines" ADD CONSTRAINT "purchase_order_lines_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sales_order_lines" ADD CONSTRAINT "sales_order_lines_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "employees" ADD CONSTRAINT "employees_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "operating_units"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "operating_units" ADD CONSTRAINT "operating_units_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "operating_units"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "operating_units" ADD CONSTRAINT "operating_units_manager_employee_id_fkey" FOREIGN KEY ("manager_employee_id") REFERENCES "employees"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "journal_entries" ADD CONSTRAINT "journal_entries_corrects_entry_id_fkey" FOREIGN KEY ("corrects_entry_id") REFERENCES "journal_entries"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "journal_lines" ADD CONSTRAINT "journal_lines_dimension_1_id_fkey" FOREIGN KEY ("dimension_1_id") REFERENCES "dimension_values"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "journal_lines" ADD CONSTRAINT "journal_lines_dimension_2_id_fkey" FOREIGN KEY ("dimension_2_id") REFERENCES "dimension_values"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "journal_lines" ADD CONSTRAINT "journal_lines_dimension_3_id_fkey" FOREIGN KEY ("dimension_3_id") REFERENCES "dimension_values"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "journal_lines" ADD CONSTRAINT "journal_lines_dimension_4_id_fkey" FOREIGN KEY ("dimension_4_id") REFERENCES "dimension_values"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "dimension_values" ADD CONSTRAINT "dimension_values_attribute_id_fkey" FOREIGN KEY ("attribute_id") REFERENCES "dimension_attributes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "dimension_rules" ADD CONSTRAINT "dimension_rules_attribute_id_fkey" FOREIGN KEY ("attribute_id") REFERENCES "dimension_attributes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "dimension_rules" ADD CONSTRAINT "dimension_rules_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "dimension_rules" ADD CONSTRAINT "dimension_rules_fixed_value_id_fkey" FOREIGN KEY ("fixed_value_id") REFERENCES "dimension_values"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "default_dimension_assignments" ADD CONSTRAINT "default_dimension_assignments_attribute_id_fkey" FOREIGN KEY ("attribute_id") REFERENCES "dimension_attributes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "default_dimension_assignments" ADD CONSTRAINT "default_dimension_assignments_value_id_fkey" FOREIGN KEY ("value_id") REFERENCES "dimension_values"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sales_parameters" ADD CONSTRAINT "sales_parameters_default_warehouse_id_fkey" FOREIGN KEY ("default_warehouse_id") REFERENCES "warehouses"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trade_agreements" ADD CONSTRAINT "trade_agreements_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trade_agreements" ADD CONSTRAINT "trade_agreements_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trade_agreements" ADD CONSTRAINT "trade_agreements_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trade_agreements" ADD CONSTRAINT "trade_agreements_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trade_agreements" ADD CONSTRAINT "trade_agreements_item_group_id_fkey" FOREIGN KEY ("item_group_id") REFERENCES "item_groups"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "factura_lines" ADD CONSTRAINT "factura_lines_factura_id_fkey" FOREIGN KEY ("factura_id") REFERENCES "facturas"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "factura_lines" ADD CONSTRAINT "factura_lines_sales_order_line_id_fkey" FOREIGN KEY ("sales_order_line_id") REFERENCES "sales_order_lines"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "factura_lines" ADD CONSTRAINT "factura_lines_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "factura_lines" ADD CONSTRAINT "factura_lines_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "factura_lines" ADD CONSTRAINT "factura_lines_item_tax_group_id_fkey" FOREIGN KEY ("item_tax_group_id") REFERENCES "item_tax_groups"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- RenameIndex
ALTER INDEX "geo_points_tenant_key_uidx" RENAME TO "geo_points_tenant_id_query_key_key";

-- RenameIndex
ALTER INDEX "geo_points_tenant_source_idx" RENAME TO "geo_points_tenant_id_source_idx";

-- RenameIndex
ALTER INDEX "inventory_batches_tenant_id_product_id_variant_id_received__idx" RENAME TO "inventory_cost_layers_tenant_id_product_id_variant_id_recei_idx";

-- RenameIndex
ALTER INDEX "journal_entries_tenant_is_correction_idx" RENAME TO "journal_entries_tenant_id_is_correction_idx";

-- RenameIndex
ALTER INDEX "product_dimension_group_lines_key" RENAME TO "product_dimension_group_lines_group_id_dimension_id_key";

-- RenameIndex
ALTER INDEX "product_dimension_groups_key" RENAME TO "product_dimension_groups_tenant_id_legal_entity_id_code_key";

-- RenameIndex
ALTER INDEX "product_dimension_value_groups_key" RENAME TO "product_dimension_value_groups_tenant_id_code_key";

-- RenameIndex
ALTER INDEX "product_dimension_values_key" RENAME TO "product_dimension_values_tenant_id_dimension_id_value_key";

-- RenameIndex
ALTER INDEX "product_dimensions_tenant_code_key" RENAME TO "product_dimensions_tenant_id_legal_entity_id_code_key";

-- RenameIndex
ALTER INDEX "product_parameters_key" RENAME TO "product_parameters_tenant_id_legal_entity_id_key";

-- RenameIndex
ALTER INDEX "product_variant_values_value_idx" RENAME TO "product_variant_values_value_id_idx";

-- RenameIndex
ALTER INDEX "warehouse_parameters_tenant_idx" RENAME TO "warehouse_parameters_tenant_id_idx";

-- RenameIndex
ALTER INDEX "warehouse_parameters_warehouse_key" RENAME TO "warehouse_parameters_warehouse_id_key";
